### ISSUE TITLE
Need usage for every feature

### ISSUE THREAD

**Issue by jindaxia** [phil65/SublimeKodi#11]
Need usage for every feature

**Comment by phil65** [comment]
What do you mean? Documentation? :)

**Comment by phil65** [comment]
Kodi Log:
- Open log from command palette
- Added syntax highlighting
- Jump to code where exception ocurred by pressing shift+enter when line with path is selected

Tooltips:
- Show english translation when label id is selected
- Show additional translation of choice when label id is selected
- show color hex value for color names
- show variable content
- show include content
- show font tag
- show constant value
- show value of selected Kodi InfoLabel in tooltip (by using JSON-RPC)
- show infos for selected image (image dimensions and file size)

JSON-RPC: (newest script.toolbox version needed)
- auto-reload skin after saving xml
- Execute builtins from command palette

Shortcuts:
- jump to include (shift+enter)
- jump to variable (shift+enter)
- jump to constant (shift+enter)
- jump to font (shift+enter)
- jump to label definition (shift+enter)
- jump to color definition (shift+enter)
- preview skin image (ctrl+enter)
- switch xml folder (ctrl+shift+enter)

Fuzzy searches:
- Search through all skin labels
- Search through all textures including preview
- Search though all available fonts

Context menu:
- move label to language file (creates entry in strings.po using the first free id and replaces selected text with $LOCAIZE[])
- go to Kodi online wiki (opens corresponding online help page, only for control types atm)

**Comment by phil65** [comment]
@jindaxia I also merged most parts of your script into a new class.
https://github.com/phil65/SublimeKodi/blob/master/libs/RemoteDevice.py
You can control that class via command palette ("SublimeKodi: Remote Actions")
I would be interested if it works for you :)
