### ISSUE TITLE
Obsessive alerts requires manual deletion of SublimeKodi

### ISSUE THREAD

**Issue by bossanova808** [phil65/SublimeKodi#13]
![2015-05-14_9-44-54](https://cloud.githubusercontent.com/assets/731309/7623522/6d8e58d4-fa1e-11e4-89df-e54ceb361436.png)

Receiving this alert obsessively to the exclusion of all else, had to kill Sublime and manually delete SublimeKodi

**Comment by bossanova808** [comment]
(Note this on a project with no XBMC involvement...)

**Comment by phil65** [comment]
try https://github.com/phil65/SublimeKodi/commit/07946e38dac26b273fd5626ee9a7af2075704a8b and report back console output. I do not get any errors with non-Kodi projects here.

**Comment by phil65** [comment]
thx for reporting.

**Comment by bossanova808** [comment]
Apologies for not getting back to you.  The uninstall process was pretty tedious as it kept re-installing to I had to manually go in to packages and remove sublimekodi to make ST3 functional. I have not had a chance yet to add it again, will probably wait till it's a bit more tested/stable.  Would definitely avoid using any blocking alerts in sublime though...

**Comment by phil65** [comment]
they only appear if you have broken xml´s or po files. For that use case it´s justified to have a blocking alert imo.

**Comment by bossanova808** [comment]
I can think of almost no other instance of a blocking alert from sublime plugins I've come across, and certainly none in projects not related to the alert, but you're writing it so entirely up to you.  

The more common approach is e.g. open an edit window with a message in it (that you can click to go to line number etc - like in find in files for example).  Sublime it all about not interfering with flow.

**Comment by phil65** [comment]
if it really happened for another project then it was a bug in software and not related to the implementation of a message dialog. Sublime Text itself throws message dialogs in case a settings dict is broken, that´s comparable to the way I use it. (and pressing enter does not interfere the flow more than adding a new view to the window)

**Comment by bossanova808** [comment]
You can see the other project in the screenshot, was definitely not xbmc related.

(I just put some garbage data into my ST user settings and I don't get a blocking alert - just BTW)

**Comment by phil65** [comment]
As I said then it´s a (rare) bug which can get fixed if you help out. I never experienced that yet.
And garbage data != malformed data. Same for the way I deal with it, garbage data doesnt matter, malformed data structs do matter. (for malformed data ST throws a dialog)

**Comment by bossanova808** [comment]
![2015-05-19_14-49-10](https://cloud.githubusercontent.com/assets/731309/7695678/6ff88e2a-fe36-11e4-99a9-2fb8f33e582b.png)

Ok, reinstalled, boom issue again (not in a kodi related project). 

Because of the dialog I can't get to the console log sorry - does this help? I will have to uninstall it again quite soon so if you need something else, repsond quickly if you can :)

**Comment by phil65** [comment]
Which exact Isengard version / date? Perhaps related to this? https://github.com/xbmc/xbmc/pull/7126

**Comment by phil65** [comment]
line number indicates yes. There you have your issue.

**Comment by bossanova808** [comment]
? It doesn't matter what version of kodi. A repeating undismissable modal
should not occur no matter the state of kodi. Double so if the project has
nothing to do with kodi.

Anyway it is probably b1 or a nightly just after iirc.

**Comment by phil65** [comment]
I will see why it pops up repeatedly. your tone sucks btw.

**Comment by phil65** [comment]
should be fixed with https://github.com/phil65/SublimeKodi/commit/998a92ca6412ee417128a184578b77314c5c0107 (untested)

**Comment by bossanova808** [comment]
I have taken time to report several bugs to help you improve your plugin.  

This particular bug is big enough to make people's Sublime Text unusable even outside of the context of a project using your plugin.  If they don't know how to manually manipulate package control, they'd have to uninstall ST3 to fix it.  So that's a pretty huge bug, really.

You're welcome it insist a modal is the right approach (I think it isn't, and I think this makes that clear, but that's just my opinion) - and of course implement it that way if  you choose - it's your plugin.  You posted it in a public place and one presumes you therefore want some help/feedback/bug reports etc, as is the way of open source.

I'm sorry if I didn't cushion the blow enough while reporting your plugin breaks things, but I was just trying to help you make it better and you seem like you seem like you have enough experience not to need the hand holding a beginner might.

Anyway, don't need or want any disagreements, I'll stay out of it from now on.  I appreciate your work and thank you for it.

**Comment by phil65** [comment]
> This particular bug is big enough to make people's Sublime Text unusable even outside of the context of a project using your plugin. If they don't know how to manually manipulate package control, they'd have to uninstall ST3 to fix it. So that's a pretty huge bug, really.

lol you're kidding, right? Everyone who uses this plugin installs it manually and will have no problems removing it manually, too. The so called "huge bug" only appears for your exact nightly version (so basically for one nightly version of the last >1000 nightlies) As you can see in forums, you're the only person who experienced it.

> (I think it isn't, and I think this makes that clear, but that's just my opinion)

What you probably dont recognize is that the loop would have the same consequences if I print into a view instead of opening a dialog: It would open that view again and again. So really pointless argument. The loop was the problem, not the message dialog.

> You posted it in a public place and one presumes you therefore want some help/feedback/bug reports etc, as is the way of open source.

The thing is: you dont even offer to help fixing bugs, all you say is "xxx is broken, xxx sucks, xxx is the wrong approach".

**Comment by bossanova808** [comment]
So far that's the case, but you said you're moving it to package control
and if this bug remains.... And if there is another unenclosed string or
whatever it was... Not too hard to imagine it repeating is it?  Maybe I am
making a bigger deal of it than it is, but there was no way I could easily
know it was just one nightly and it broke my st3 pretty completely for a
bit.

If it was in a view it would print into the view, and that view would be in
the background like other such views in other plugins and one could then
probably reach package control to uninstall. I think that would be better,
you don't. Fine.  Agree to disagree.

I reported the bug with plenty of info, reinstalled it though it broke my
st3 to the point of unusable, to help you isolate it further,  & never said
anything sucked or close to it.  I didn't sugar coat it but I can't see me
being anything other than factual.

I am sorry I have offended you - i did so without meaning to.  Let's move
on eh?  Life is too short, and this is not that important.

**Comment by phil65** [comment]
> So far that's the case, but you said you're moving it to package control and if this bug remains.... And if there is another unenclosed string or whatever it was... Not too hard to imagine it repeating is it? Maybe I am making a bigger deal of it than it is, but there was no way I could easily know it was just one nightly and it broke my st3 pretty completely for a bit.

You got the name of the file in console and the line number in the dialog so it is not too hard to find the root cause, is it?

> If it was in a view it would print into the view, and that view would be in
> the background like other such views in other plugins and one could then
> probably reach package control to uninstall. I think that would be better,
> you don't. Fine.  Agree to disagree.

You really think anything would work if you write to a view in an endless loop?
Also, show me any plug-in which displays a small error message by creating a new view.
(I just took a quick look, Anaconda as the most popular python IDE in ST also uses a message dialog for severe errors btw)

> I reported the bug with plenty of info, reinstalled it though it broke my st3 to the point of unusable, to help you isolate it further,

-ridiculous. You posted a screenshot + a one-liner. No word about when it happened exactly, no complete console output, nothing else. I also didnt know that people who describe themselves as factual use wording like "obsessively" in bug reports. That's really new to me.

**Comment by bossanova808** [comment]
Ok. Like I said life is too short, don't enjoy arguing, wish I hadn't
wasted my time.

**Comment by phil65** [comment]
No worries. The time you win by using this plugin will make up for it.
