### ISSUE TITLE
exception on windows 7 32bit

### ISSUE THREAD

**Issue by jindaxia** [phil65/SublimeKodi#14]
File "C:\Users\jindaxia\AppData\Roaming\Sublime Text 3\Packages\SublimeKodi\sublimekodi.py", line 13, in <module>
    from lxml import etree as ET
ImportError: DLL load failed: %1 不是有效的 Win32 应用程序。

**Comment by phil65** [comment]
I cannot read chinese :)
since when does that appear?

**Comment by jindaxia** [comment]
ImportError: DLL load failed: %1 is not a valid Win32 application

**Comment by jindaxia** [comment]
i know the reason,  i use the 32bit sublimetext on 64bit os

**Comment by jindaxia** [comment]
when i use 32bit sublitext 3088 on win7 32bit , i see the same error

**Comment by phil65** [comment]
for now you could replace the libs from pillow and lxml with win32 libs.
http://www.lfd.uci.edu/~gohlke/pythonlibs/
you need the win32 libs for Python3.3.

**Comment by jindaxia** [comment]
there is no lxml libs on this site

**Comment by phil65** [comment]
lxml is also there:
http://www.lfd.uci.edu/~gohlke/pythonlibs/#lxml
does it work?

**Comment by phil65** [comment]
ping @jindaxia

**Comment by jindaxia** [comment]
it works
