### ISSUE TITLE
Mac support

### ISSUE THREAD

**Issue by ghost** [phil65/SublimeKodi#20]
Thanks for you help already in trying to get this working on Mac. You said in that conversation you didn't have any requests for Mac support yet, so I thought I'd be the first to do so ;)

I've been trying to get it working, following your advice that I need to replace the precompiled lxml and Pillow libraries with ones built on Mac, but am not having much luck. I'm happy for now to use it via a Windows VM, but if you have any ideas what might be going wrong...

I've started with lxml, following the instructions at http://lxml.de/build.html#building-lxml-on-macos-x to build from source. Tested this build works with

```
>>> from lxml import etree as ET
>>> ET
<module 'lxml.etree' from '/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/lxml-3.4.3-py3.4-macosx-10.6-intel.egg/lxml/etree.so'>
>>>
```

Then copied the library into the SublimeKodi package, replacing the contents of the libs/lxml folder. On starting SublimeText, it doesn't appear that the etree module can be imported - with the following in the log

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 74, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/Users/borkable/Library/Application Support/Sublime Text 3/Packages/SublimeKodi/sublimekodi.py", line 25, in <module>
    from lxml import etree as ET
ImportError: dlopen(/Users/borkable/Library/Application Support/Sublime Text 3/Packages/SublimeKodi/libs/lxml/etree.so, 2): Symbol not found: _PyObject_CallFinalizerFromDealloc
  Referenced from: /Users/borkable/Library/Application Support/Sublime Text 3/Packages/SublimeKodi/libs/lxml/etree.so
  Expected in: flat namespace
 in /Users/borkable/Library/Application Support/Sublime Text 3/Packages/SublimeKodi/libs/lxml/etree.so
```

At that point this goes way past both my skill and googling level. As I say, if you have any ideas, otherwise a VM it is :)

Cheers.

**Comment by phil65** [comment]
```
/python3.4/
```

that is probably the issue. :)
compile against python 3.3.

**Comment by ghost** [comment]
I was really hoping you weren't going to say that ;) My attempts to install Python 3.3 weren't successful, probably because I'm on a beta version of osX. Thanks for the hint, though.

**Comment by phil65** [comment]
perhaps you can set up another VM with non-beta osx to compile it?

**Comment by ghost** [comment]
I'm going to try to build Python from source. If that doesn't work then that'll be my next attempt.

**Comment by phil65** [comment]
ok. good luck. ;)

**Comment by ghost** [comment]
Finally got it working. Thanks again for your help :)

**Comment by phil65** [comment]
Great. If you have any further ideas for that add-on then let me know.
Also, a pull request for your OSX fix would be welcome (as long as it doesnt break linux / windows :) )

**Comment by ghost** [comment]
Unfortunately my solution does break Linux/Windows, as it replaces lxml/Pillow for those platforms. This really isn't my area, so I've no idea how this should be handled properly (or, if I'm honest, the desire to learn), but I'm quite happy to maintain a Mac fork for the foreseeable :)

**Comment by phil65** [comment]
Windows is no problem (it uses the .pyd file), only Linux is problematic. (also uses .so file).
Anyway, I will just wait for the next person to stumble across this problem. :)

**Comment by ghost** [comment]
Yup, that's about as far as I got with the issue ;) From what I understand, either Mac or Linux would need to be built differently - so that one or the other would be lxml-mac & PIL-mac / lxml-linux & PIL-linux (for example), so they could be included dependant on the OS. That's where I stopped looking, as I've just used PIP to install + build them and have no idea how to even start building with such options - I've never gone beyond the typical ./configure/make/make install, let alone custom build these libraries! (Oh, and I suspect we'd need to use the same versions - which we currently aren't doing for at least Pillow, though at least that's easy enough - you just need to upgrade ;))

But, as you say, can wait for the next idiot to use Mac to stumble across the issue :P

**Comment by phil65** [comment]
Yeah I am also no expert when it comes to those buildchain/compiling-related problems.
As for PIL / pillow, I would prefer to simply completely get rid of it since I only use it for reading image dimensions and I am convinced that there has to be a "lighter" solution. I couldnt get any other solution available to work with the ST3 interpreter though (perhaps I didnt research enough), that´s why it´s still in there.

**Comment by ghost** [comment]
Hmm. Y'know how you sometimes just try things...

I've just tried

```
try:
    import lxml
except:
    import lxml-mac as lxml
```

Which has worked fine - from a very quick test, and obviously renaming the folder containing the Mac version of lxml. I'll give it a proper test tomorrow, but you never know, it may be as simple as that...

**Comment by phil65** [comment]
I expect the solution to be very simple, but without confirmation I won´t commit anything in that direction :)
Thx for givin it a shot.

**Comment by ghost** [comment]
Understandable. If it still works in the morning, though, I'll send you a PR to confirm that it doesn't break anything on Windows/Linux ;)

**Comment by phil65** [comment]
Fine. Thx and have a good night.
