### ISSUE TITLE
settings file name issue

### ISSUE THREAD

**Issue by jindaxia** [phil65/SublimeKodi#25]
kodidevkit.py line 40

``` Python
SETTINGS_FILE = 'sublimekodi.sublime-settings'
```

MainMenu

``` json
file": "${packages}/KodiDevKit/sublimekodi.sublime-settings"
```

but the settings file name is 
`kodidevkit.sublime-settings`

**Comment by phil65** [comment]
This repo is outdated. See

https://packagecontrol.io/packages/KodiDevKit
https://github.com/phil65/KodiDevKit
